package cavendish_main;

/**
 *
 * @author Baguy
 */
public class FormularioGUI extends javax.swing.JFrame {
    
    private InicialGUI telaANTERIOR;
    
    /**
     * Creates new form fFORMULARIO
     */
    public FormularioGUI() {
        initComponents();
        myInitComponents();
    }
    
    // ♥ criar inicialização dos componentes personalizada
   // ♥ Netbeans não permite edição no método -- private void initComponents()
    public void myInitComponents() {

        // ♥ cor do texto preto
        jSEXO.setForeground(java.awt.Color.BLACK);
        jCABELO.setForeground(java.awt.Color.BLACK);
        jCARACTERISTICA.setForeground(java.awt.Color.BLACK);
        jPROVA.setForeground(java.awt.Color.BLACK);
        jACESSORIO.setForeground(java.awt.Color.BLACK);
        jNOME.setForeground(java.awt.Color.RED);
        
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMANDADO = new javax.swing.JLabel();
        jSEXO = new javax.swing.JLabel();
        caixaSEXO = new javax.swing.JComboBox<>();
        caixaCARACTERISTICA = new javax.swing.JComboBox<>();
        caixaPROVAS = new javax.swing.JComboBox<>();
        jCARACTERISTICA = new javax.swing.JLabel();
        jPROVA = new javax.swing.JLabel();
        caixaCABELO = new javax.swing.JComboBox<>();
        jCABELO = new javax.swing.JLabel();
        jMOLDURA = new javax.swing.JLabel();
        jVOLTAR = new javax.swing.JLabel();
        jEXPEDIR = new javax.swing.JLabel();
        jPISTAS = new javax.swing.JLabel();
        caixaACESSORIO = new javax.swing.JComboBox<>();
        jACESSORIO = new javax.swing.JLabel();
        jDOSSIE = new javax.swing.JLabel();
        jNOME = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(830, 650));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(130, 148, 190));
        jPanel1.setLayout(null);

        jMANDADO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMANDADO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cavendish_main/botoes/MANDADOdeprisao.png"))); // NOI18N
        jPanel1.add(jMANDADO);
        jMANDADO.setBounds(100, -10, 660, 120);

        jSEXO.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 22)); // NOI18N
        jSEXO.setText("Sexo");
        jPanel1.add(jSEXO);
        jSEXO.setBounds(40, 170, 100, 26);

        caixaSEXO.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        caixaSEXO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "?", "Mulher", "Homem" }));
        jPanel1.add(caixaSEXO);
        caixaSEXO.setBounds(180, 170, 286, 23);

        caixaCARACTERISTICA.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        caixaCARACTERISTICA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "?", "Cicatriz", "Tatuagem", "Queimadura", "Tapa-olho" }));
        jPanel1.add(caixaCARACTERISTICA);
        caixaCARACTERISTICA.setBounds(180, 280, 286, 23);

        caixaPROVAS.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        caixaPROVAS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "?", "Foto", "Impressão digital", "DNA", "Pegada" }));
        jPanel1.add(caixaPROVAS);
        caixaPROVAS.setBounds(180, 330, 286, 23);

        jCARACTERISTICA.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 22)); // NOI18N
        jCARACTERISTICA.setText("Característica");
        jPanel1.add(jCARACTERISTICA);
        jCARACTERISTICA.setBounds(40, 270, 130, 40);

        jPROVA.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 22)); // NOI18N
        jPROVA.setText("Evidência");
        jPanel1.add(jPROVA);
        jPROVA.setBounds(40, 320, 130, 40);

        caixaCABELO.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        caixaCABELO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "?", "Preto", "Castanho", "Loiro", "Ruivo", "Colorido" }));
        jPanel1.add(caixaCABELO);
        caixaCABELO.setBounds(180, 220, 286, 23);

        jCABELO.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 22)); // NOI18N
        jCABELO.setText("Cabelo");
        jPanel1.add(jCABELO);
        jCABELO.setBounds(40, 220, 110, 40);

        jMOLDURA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMOLDURA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cavendish_main/botoes/moldura.png"))); // NOI18N
        jPanel1.add(jMOLDURA);
        jMOLDURA.setBounds(500, 160, 273, 319);

        jVOLTAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jVOLTAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cavendish_main/botoes/bVOLTAR.png"))); // NOI18N
        jVOLTAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jVOLTARMouseClicked(evt);
            }
        });
        jPanel1.add(jVOLTAR);
        jVOLTAR.setBounds(30, 491, 130, 96);

        jEXPEDIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cavendish_main/botoes/baseEXPEDIR.png"))); // NOI18N
        jPanel1.add(jEXPEDIR);
        jEXPEDIR.setBounds(249, 417, 164, 170);

        jPISTAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cavendish_main/botoes/bPISTAS.png"))); // NOI18N
        jPanel1.add(jPISTAS);
        jPISTAS.setBounds(10, 0, 110, 140);

        caixaACESSORIO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "?", "Brinco", "Corrente", "Chapéu", "Óculos" }));
        jPanel1.add(caixaACESSORIO);
        caixaACESSORIO.setBounds(180, 380, 290, 22);

        jACESSORIO.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 22)); // NOI18N
        jACESSORIO.setText("Acessório");
        jPanel1.add(jACESSORIO);
        jACESSORIO.setBounds(40, 380, 120, 20);

        jDOSSIE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cavendish_main/botoes/bDOSSIE.png"))); // NOI18N
        jPanel1.add(jDOSSIE);
        jDOSSIE.setBounds(490, 490, 160, 100);

        jNOME.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jNOME.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jNOME);
        jNOME.setBounds(170, 100, 590, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jVOLTARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jVOLTARMouseClicked
        
        // ♥ fechar janela ao clicar botão VOLTAR
        this.dispose();

        // ♥ reabilitar a  janela anterior (tela INICIAL) que foi desabilitada...
        // ♥ ...quando clicou-se no botão CADASTRAR
        //telaANTERIOR.setEnabled(true);
        
    }//GEN-LAST:event_jVOLTARMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> caixaACESSORIO;
    private javax.swing.JComboBox<String> caixaCABELO;
    private javax.swing.JComboBox<String> caixaCARACTERISTICA;
    private javax.swing.JComboBox<String> caixaPROVAS;
    private javax.swing.JComboBox<String> caixaSEXO;
    private javax.swing.JLabel jACESSORIO;
    private javax.swing.JLabel jCABELO;
    private javax.swing.JLabel jCARACTERISTICA;
    private javax.swing.JLabel jDOSSIE;
    private javax.swing.JLabel jEXPEDIR;
    private javax.swing.JLabel jMANDADO;
    private javax.swing.JLabel jMOLDURA;
    private javax.swing.JLabel jNOME;
    private javax.swing.JLabel jPISTAS;
    private javax.swing.JLabel jPROVA;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jSEXO;
    private javax.swing.JLabel jVOLTAR;
    // End of variables declaration//GEN-END:variables
}
