package cavendish_main;

import java.awt.Toolkit;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Baguy
 */

public class InicialGUI extends javax.swing.JFrame {

    // ♥ definir "minimumSize" como [830, 650] para a tela abrir do...
    // ♥ ...tamanho correto [800, 600]
    
    /**
     * Creates new form ftelaINICIAL
     */
    public InicialGUI() {
        initComponents();
        // ♥ inicializar meus componentes personalizados
        myInitComponents();
    }
    
   // ♥ criar inicialização dos componentes personalizado
   // ♥ Netbeans não permite edição no método -- private void initComponents()
    public void myInitComponents() {
        
        // ♥ deixar caixa de texto -- jNOMEUSUÁRIO -- com fundo transparente
        jNOMEUSUARIO.setOpaque(false);
        // ♥ deixar borda da caixa texto transparente
        jNOMEUSUARIO.setBorder(null);
        
}    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLOGIN = new javax.swing.JLabel();
        jCADASTRAR = new javax.swing.JLabel();
        jNOMEUSUARIO = new javax.swing.JTextField();
        jcaixaTEXTO = new javax.swing.JLabel();
        jtelaINICIAL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("O segredo de Cavendish");
        setMinimumSize(new java.awt.Dimension(820, 650));
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 0, 600);

        jLOGIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cavendish_main/botoes/bLOGIN.png"))); // NOI18N
        jLOGIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLOGINMouseClicked(evt);
            }
        });
        getContentPane().add(jLOGIN);
        jLOGIN.setBounds(120, 370, 160, 110);

        jCADASTRAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cavendish_main/botoes/bCADASTRAR.png"))); // NOI18N
        jCADASTRAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCADASTRARMouseClicked(evt);
            }
        });
        getContentPane().add(jCADASTRAR);
        jCADASTRAR.setBounds(320, 370, 190, 110);

        jNOMEUSUARIO.setBackground(javax.swing.UIManager.getDefaults().getColor("menu"));
        jNOMEUSUARIO.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jNOMEUSUARIO.setForeground(new java.awt.Color(255, 255, 255));
        jNOMEUSUARIO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jNOMEUSUARIO.setToolTipText("nome de usuário");
        jNOMEUSUARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNOMEUSUARIOActionPerformed(evt);
            }
        });
        getContentPane().add(jNOMEUSUARIO);
        jNOMEUSUARIO.setBounds(80, 280, 480, 50);

        jcaixaTEXTO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cavendish_main/botoes/cTEXTO.png"))); // NOI18N
        getContentPane().add(jcaixaTEXTO);
        jcaixaTEXTO.setBounds(50, 260, 540, 90);

        jtelaINICIAL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cavendish_main/fundos/telaINICIAL.png"))); // NOI18N
        getContentPane().add(jtelaINICIAL);
        jtelaINICIAL.setBounds(0, 0, 800, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // ♥ BOTÃO LOGIN quando clicado
    private void jLOGINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLOGINMouseClicked
         
        // ♥ confirmar LOGIN...
        String login = jNOMEUSUARIO.getText();        
        
        // ♥ caso LOGIN confirmado, começar jogo
        // ♥ abre outra tela --> JogoGUI
        // ♥ para fechar a tela inicial e ficar apenas a JogoGUI aberta
        this.dispose();
        new JogoGUI(this).setVisible(true);
    

    }//GEN-LAST:event_jLOGINMouseClicked

      
    
    // ♥ botão CADASTRO quando clicado
    private void jCADASTRARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCADASTRARMouseClicked
        
        // ♥ desabilitar a tela INICIAL temporariamente para usuário...
        // ♥ ...não poder abrir várias telas de cadastro
        this.setEnabled(false);
        
        // ♥ Quando clicar no jCADASTRAR (botão CADASTRAR) -> aparecer tela de casdastro
        new CadastrarGUI(this).setVisible(true);
        
    }//GEN-LAST:event_jCADASTRARMouseClicked

    
    
    private void jNOMEUSUARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNOMEUSUARIOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNOMEUSUARIOActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicialGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicialGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicialGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicialGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                
                new InicialGUI().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jCADASTRAR;
    public javax.swing.JLabel jLOGIN;
    public static javax.swing.JTextField jNOMEUSUARIO;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel jcaixaTEXTO;
    public javax.swing.JLabel jtelaINICIAL;
    // End of variables declaration//GEN-END:variables
}
