package cavendish_main;

import java.awt.Color;
import java.util.Random;


public class JogoGUI extends javax.swing.JFrame {

    /**
     * Creates new form JogoGUI
     */
    
    // ♥ objetos e variáveis globais
    public int faseAtual=0;
    public int cidadeAtual=0;
    Imagens imagem = new Imagens();
    private InicialGUI telaANTERIOR;
    int botaoApertadoPERGAMINHO = 1;
    Fase fase = new Fase();
    Random aleatorio = new Random();
    int num;
    Cidade tempCidade= new Cidade();


    // ♥ variável global para saber qual local o jogador selecionou
        int selecionado = 0;

    
    public JogoGUI() {
        initComponents();
        myInitComponents();
    }
    
    // ♥ para fechar tela anterior
    public JogoGUI(InicialGUI telaANTERIOR){
        this();
        this.telaANTERIOR = telaANTERIOR;
        
    }
    
    // ♥ criar inicialização dos componentes personalizada
   // ♥ Netbeans não permite edição no método -- private void initComponents()
    public void myInitComponents() {
        
        jTITULO.setOpaque(false);
        jTITULO.setBorder(null);
        jTITULO.setEditable(false);
        jtextoAZUL.setOpaque(false);
        // ♥ NÃO FUNCIONANDO -- fundo da caixa de texto grande não está transparente
        jtextoAZUL.setBorder(null);
        jtextoAZUL.setEditable(false);
        
        // ♥ textos na cor preta
        jtextoLUGAR1.setForeground(Color.BLACK);
        jtextoLUGAR2.setForeground(Color.BLACK);
        jtextoLUGAR3.setForeground(Color.BLACK);
        jtextoAZUL.setForeground(Color.BLACK);
        jtextoPERGAMINHO.setForeground(java.awt.Color.BLACK);
        
        
        
        //Aru - DESABILITANDO A VISIBILIDADE REFERENTE AOS BOTOES DE INVESTIGAÇÃO
        jtextoLUGAR1.setVisible(false);
        jtextoLUGAR2.setVisible(false);
        jtextoLUGAR3.setVisible(false);
        jescolhaLugarFUNDO1.setVisible(false);
        jescolhaLugarFUNDO2.setVisible(false);
        jescolhaLugarFUNDO3.setVisible(false);
        jescolhaLugarFUNDO4.setVisible(false);
        jescolhaLugarFUNDO5.setVisible(false);
        jescolhaLugarFUNDO6.setVisible(false);
        jMAPA.setVisible(false);
        jcaixaAZUL.setVisible(false);
        jtextoScrollAZUL.setVisible(false);
        jTITULO.setVisible(false);
        jPISTAS.setVisible(false);
        jINVESTIGAR.setVisible(false);
        jLOCAIS.setVisible(false);
        jSAIBAMAIS.setVisible(false);
        jtextoLUGAR1.setVisible(false);
        jtextoLUGAR2.setVisible(false);
        jtextoLUGAR3.setVisible(false);
        jcaixaAZUL.setVisible(false);
        jtextoScrollAZUL.setVisible(false);
        jcaixaGrandeAZUL2.setVisible(false);
        
        
        // ♥ para o usuário não poder editar o texto
        jtextoPERGAMINHO.setEditable(false);
        jtextoAZUL.setEditable(false);
        
        
        // ♥ --------- TEXTO inicial PERGAMINHO
        // ♥ sem bordas na caixa texto do pergaminho
        jtextoScrollPERGAMINHO.setBorder(null);

                String bla = (" \n Bem-vindo, \n"
                        // ♥ nome do usuário depende do LOGIN validado
                        +"   "+ "_________________"+InicialGUI.jNOMEUSUARIO.getText() +
                        "\n seu posto atual é: \n"
                        // ♥ lembrar de pegar "posto atual" dependendo do save do jogador!
                        + "   __________ ");
                
                jtextoPERGAMINHO.setText(bla);
 
                System.out.println(bla);
        // ♥ --------- \
        


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTITULO = new javax.swing.JTextField();
        jLOCAIS = new javax.swing.JLabel();
        jINVESTIGAR = new javax.swing.JLabel();
        jPISTAS = new javax.swing.JLabel();
        jSAIBAMAIS = new javax.swing.JLabel();
        jMAPA = new javax.swing.JLabel();
        jtextoScrollAZUL = new javax.swing.JScrollPane();
        jtextoAZUL = new javax.swing.JTextArea();
        jtextoLUGAR1 = new javax.swing.JLabel();
        jtextoLUGAR2 = new javax.swing.JLabel();
        jtextoLUGAR3 = new javax.swing.JLabel();
        jcaixaAZUL = new javax.swing.JLabel();
        jescolhaLugarFUNDO2 = new javax.swing.JLabel();
        jescolhaLugarFUNDO6 = new javax.swing.JLabel();
        jescolhaLugarFUNDO3 = new javax.swing.JLabel();
        jescolhaLugarFUNDO5 = new javax.swing.JLabel();
        jescolhaLugarFUNDO1 = new javax.swing.JLabel();
        jescolhaLugarFUNDO4 = new javax.swing.JLabel();
        jtextoScrollPERGAMINHO = new javax.swing.JScrollPane();
        jtextoPERGAMINHO = new javax.swing.JTextArea();
        jCONTINUAR = new javax.swing.JLabel();
        jTESTEMUNHA = new javax.swing.JLabel();
        jFUNDO = new javax.swing.JLabel();
        jcaixaGrandeAZUL2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(830, 650));
        getContentPane().setLayout(null);

        jTITULO.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jTITULO.setForeground(new java.awt.Color(255, 255, 255));
        jTITULO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTITULO.setAutoscrolls(false);
        jTITULO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTITULOActionPerformed(evt);
            }
        });
        getContentPane().add(jTITULO);
        jTITULO.setBounds(40, 370, 670, 40);

        jLOCAIS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cavendish_main/botoes/bLOCAIS.png"))); // NOI18N
        jLOCAIS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLOCAISMouseClicked(evt);
            }
        });
        getContentPane().add(jLOCAIS);
        jLOCAIS.setBounds(10, 0, 90, 120);

        jINVESTIGAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cavendish_main/botoes/bINVESTIGAR.png"))); // NOI18N
        jINVESTIGAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jINVESTIGARMouseClicked(evt);
            }
        });
        getContentPane().add(jINVESTIGAR);
        jINVESTIGAR.setBounds(10, 120, 100, 120);

        jPISTAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cavendish_main/botoes/bPISTAS.png"))); // NOI18N
        jPISTAS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPISTASMouseClicked(evt);
            }
        });
        getContentPane().add(jPISTAS);
        jPISTAS.setBounds(10, 240, 100, 110);

        jSAIBAMAIS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cavendish_main/botoes/bSAIBA.png"))); // NOI18N
        getContentPane().add(jSAIBAMAIS);
        jSAIBAMAIS.setBounds(710, 540, 90, 60);

        jMAPA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMAPA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cavendish_main/botoes/bMAPA.png"))); // NOI18N
        jMAPA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMAPAMouseClicked(evt);
            }
        });
        getContentPane().add(jMAPA);
        jMAPA.setBounds(340, 0, 120, 50);

        jtextoAZUL.setColumns(20);
        jtextoAZUL.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 20)); // NOI18N
        jtextoAZUL.setRows(5);
        jtextoScrollAZUL.setViewportView(jtextoAZUL);

        getContentPane().add(jtextoScrollAZUL);
        jtextoScrollAZUL.setBounds(70, 430, 640, 150);

        jtextoLUGAR1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jtextoLUGAR1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jtextoLUGAR1.setText("PICO DO CORCOVADO");
        getContentPane().add(jtextoLUGAR1);
        jtextoLUGAR1.setBounds(200, 80, 400, 50);

        jtextoLUGAR2.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jtextoLUGAR2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jtextoLUGAR2.setText("ILHA DAS COUVES");
        getContentPane().add(jtextoLUGAR2);
        jtextoLUGAR2.setBounds(200, 180, 400, 40);

        jtextoLUGAR3.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jtextoLUGAR3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jtextoLUGAR3.setText("PROJETO TAMAR");
        getContentPane().add(jtextoLUGAR3);
        jtextoLUGAR3.setBounds(200, 270, 380, 40);

        jcaixaAZUL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cavendish_main/botoes/cgTEXTO2.png"))); // NOI18N
        getContentPane().add(jcaixaAZUL);
        jcaixaAZUL.setBounds(0, 350, 800, 250);

        jescolhaLugarFUNDO2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jescolhaLugarFUNDO2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cavendish_main/botoes/cTEXTO2.png"))); // NOI18N
        jescolhaLugarFUNDO2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jescolhaLugarFUNDO2MouseClicked(evt);
            }
        });
        getContentPane().add(jescolhaLugarFUNDO2);
        jescolhaLugarFUNDO2.setBounds(0, 160, 800, 80);

        jescolhaLugarFUNDO6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jescolhaLugarFUNDO6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cavendish_main/botoes/cTEXTO2.png"))); // NOI18N
        jescolhaLugarFUNDO6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jescolhaLugarFUNDO6MouseClicked(evt);
            }
        });
        getContentPane().add(jescolhaLugarFUNDO6);
        jescolhaLugarFUNDO6.setBounds(0, 160, 800, 80);

        jescolhaLugarFUNDO3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jescolhaLugarFUNDO3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cavendish_main/botoes/cTEXTO2.png"))); // NOI18N
        jescolhaLugarFUNDO3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jescolhaLugarFUNDO3MouseClicked(evt);
            }
        });
        getContentPane().add(jescolhaLugarFUNDO3);
        jescolhaLugarFUNDO3.setBounds(0, 250, 800, 80);

        jescolhaLugarFUNDO5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jescolhaLugarFUNDO5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cavendish_main/botoes/cTEXTO2.png"))); // NOI18N
        jescolhaLugarFUNDO5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jescolhaLugarFUNDO5MouseClicked(evt);
            }
        });
        getContentPane().add(jescolhaLugarFUNDO5);
        jescolhaLugarFUNDO5.setBounds(0, 250, 800, 80);

        jescolhaLugarFUNDO1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jescolhaLugarFUNDO1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cavendish_main/botoes/cTEXTO2.png"))); // NOI18N
        jescolhaLugarFUNDO1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jescolhaLugarFUNDO1MouseClicked(evt);
            }
        });
        getContentPane().add(jescolhaLugarFUNDO1);
        jescolhaLugarFUNDO1.setBounds(0, 60, 800, 90);

        jescolhaLugarFUNDO4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jescolhaLugarFUNDO4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cavendish_main/botoes/cTEXTO2.png"))); // NOI18N
        jescolhaLugarFUNDO4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jescolhaLugarFUNDO4MouseClicked(evt);
            }
        });
        getContentPane().add(jescolhaLugarFUNDO4);
        jescolhaLugarFUNDO4.setBounds(0, 60, 800, 90);

        jtextoPERGAMINHO.setBackground(new java.awt.Color(213, 173, 104));
        jtextoPERGAMINHO.setColumns(20);
        jtextoPERGAMINHO.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jtextoPERGAMINHO.setRows(5);
        jtextoScrollPERGAMINHO.setViewportView(jtextoPERGAMINHO);

        getContentPane().add(jtextoScrollPERGAMINHO);
        jtextoScrollPERGAMINHO.setBounds(110, 130, 570, 340);

        jCONTINUAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCONTINUAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cavendish_main/botoes/bCONTINUAR.png"))); // NOI18N
        jCONTINUAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCONTINUARMouseClicked(evt);
            }
        });
        getContentPane().add(jCONTINUAR);
        jCONTINUAR.setBounds(0, 480, 800, 120);
        getContentPane().add(jTESTEMUNHA);
        jTESTEMUNHA.setBounds(0, 0, 800, 600);

        jFUNDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cavendish_main/fundos/pergaminho.png"))); // NOI18N
        getContentPane().add(jFUNDO);
        jFUNDO.setBounds(0, 0, 800, 600);

        jcaixaGrandeAZUL2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cavendish_main/botoes/cgTEXTO2.png"))); // NOI18N
        getContentPane().add(jcaixaGrandeAZUL2);
        jcaixaGrandeAZUL2.setBounds(0, 350, 800, 250);

        jPanel1.setBackground(new java.awt.Color(130, 148, 190));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTITULOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTITULOActionPerformed
        
    }//GEN-LAST:event_jTITULOActionPerformed

    // ♥ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ opção LOCAIS
    // ♥ se lugar 1 for selecionado
    private void jescolhaLugarFUNDO1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jescolhaLugarFUNDO1MouseClicked
        selecionado = 1;
        imagem.trocar(tempCidade.local1.fundo, jFUNDO);
        jTITULO.setText(tempCidade.local1.nome);
        jtextoAZUL.setText(tempCidade.local1.descricao);
        investigarOFF();
        bInvestigarON(); 
        bMapaOpcoesOFF();
        
    }//GEN-LAST:event_jescolhaLugarFUNDO1MouseClicked

    // ♥ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ opção LOCAIS
    // ♥ se lugar 2 for selecionado
    private void jescolhaLugarFUNDO2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jescolhaLugarFUNDO2MouseClicked
        selecionado = 2;
        imagem.trocar(tempCidade.local2.fundo, jFUNDO);
        jTITULO.setText(tempCidade.local2.nome);
        jtextoAZUL.setText(tempCidade.local2.descricao);
        investigarOFF();
        bInvestigarON(); 
        bMapaOpcoesOFF();

        
    }//GEN-LAST:event_jescolhaLugarFUNDO2MouseClicked

    // ♥ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ LOCAIS
    // ♥ clicar botão LOCAIS
    private void jLOCAISMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLOCAISMouseClicked
        
        investigarON();//Aru - HABILITA BOTÕES DOS ATRATIVOS DA FASE
        //myInitComponents(); //Aru - RECARREGA COMPONENTES DA TELA INICIAL

        jTESTEMUNHA.setVisible(false);
        bMapaON();
        bMapaOpcoesOFF();        
 
        
    }//GEN-LAST:event_jLOCAISMouseClicked

    // ♥ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ INVESTIGAR
    // ♥ clicar botão INVESTIGAR
    private void jINVESTIGARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jINVESTIGARMouseClicked
      
    switch (selecionado){
        case 1:
            imagem.trocar(tempCidade.local1.testemunha, jTESTEMUNHA);
            jTITULO.setText(tempCidade.local1.testemunhaNome);
            //if para se for final da fase pegar pista correta
            jtextoAZUL.setText(tempCidade.prox.getPista());
                              
        break;
        
        case 2:
            imagem.trocar(tempCidade.local2.testemunha, jTESTEMUNHA);
            jTITULO.setText(tempCidade.local2.testemunhaNome);
            //if para se for final da fase pegar pista correta
            jtextoAZUL.setText(tempCidade.prox.getPista());
            
        break;
        case 3:
            imagem.trocar(tempCidade.local3.testemunha, jTESTEMUNHA);
            jTITULO.setText(tempCidade.local3.testemunhaNome);
            //if para se for final da fase pegar pista correta
            jtextoAZUL.setText(tempCidade.prox.getPista());
            
        break;
    }
       jTESTEMUNHA.setVisible(true);
        
    }//GEN-LAST:event_jINVESTIGARMouseClicked

    // ♥ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ PISTAS
    // ♥ clicar botão PISTAS
    private void jPISTASMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPISTASMouseClicked
        
        new FormularioGUI().setVisible(true);
        
    }//GEN-LAST:event_jPISTASMouseClicked

    // ♥ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ opção LOCAIS
    // ♥ se lugar 3 for selecionado
    private void jescolhaLugarFUNDO3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jescolhaLugarFUNDO3MouseClicked
        selecionado = 3;
        imagem.trocar(tempCidade.local3.fundo, jFUNDO);
        jTITULO.setText(tempCidade.local3.nome);
        jtextoAZUL.setText(tempCidade.local3.descricao);
        investigarOFF();
        bInvestigarON(); 
        bMapaOpcoesOFF();
        
    }//GEN-LAST:event_jescolhaLugarFUNDO3MouseClicked

    // ♥ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ MAPA
    // ♥ botão MAPA
    private void jMAPAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMAPAMouseClicked
        
        imagem.trocar("fundos/mapa.png", jFUNDO);
        jtextoLUGAR1.setText(tempCidade.nomeCidade);
        jtextoLUGAR2.setText(tempCidade.prox.nomeCidade);
        jtextoLUGAR3.setText(tempCidade.prox.prox.nomeCidade);
        jescolhaLugarFUNDO4.setVisible(true); jescolhaLugarFUNDO4.setEnabled(true);
        jescolhaLugarFUNDO5.setVisible(true); jescolhaLugarFUNDO5.setEnabled(true);
        jescolhaLugarFUNDO6.setVisible(true); jescolhaLugarFUNDO6.setEnabled(true);
        bLocaisOpcoesOFF();
        
        
       
    }//GEN-LAST:event_jMAPAMouseClicked

    // ♥ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ CONTINUAR PERGAMINHO
    // ♥ botão CONTINUAR do pergaminho
    private void jCONTINUARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCONTINUARMouseClicked
        
        // ♥ quando apertado 1ª vez -- trocar texto do pergaminho pela explicação da fase

        //CRIAÇÃO DE OBJETO TEMPORÁRIO QUE RECEBE CIDADE ATUAL
            tempCidade = fase.listaFases[0].vetCidades[0];
            tempCidade.prox = fase.listaFases[0].vetCidades[1];
            tempCidade.prox.ant = fase.listaFases[0].vetCidades[0];
            tempCidade.prox.prox = fase.listaFases[0].vetCidades[2];
            tempCidade.prox.prox.ant = fase.listaFases[0].vetCidades[2];
        System.out.println("Temp cidade: " + tempCidade.nomeCidade);
        System.out.println("tempCidade.prox: " + tempCidade.prox.nomeCidade);
        System.out.println("tempCidade.prox.prox: " + tempCidade.prox.prox.nomeCidade);

        if( botaoApertadoPERGAMINHO == 1 ){
            
            jtextoPERGAMINHO.setText(fase.listaFases[faseAtual].textoPergaminho);
            botaoApertadoPERGAMINHO++;
            
        }else
        // ♥ quando apertado 2ª vez -- começar fase
        if( botaoApertadoPERGAMINHO == 2 ) {
                    
            pergaminhoOFF();

            imagem.trocar(tempCidade.fundo, jFUNDO);
            jTITULO.setText(tempCidade.nomeCidade);
            jtextoScrollAZUL.setVisible(true);
            jtextoAZUL.setText(tempCidade.cidadeDescricao);
            bLocalON();
            bPistasON();
            bInvestigarON ();
            jSAIBAMAIS.setVisible(true);
            
            
        }
        
    }//GEN-LAST:event_jCONTINUARMouseClicked

    // ♥ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ opções MAPA
    // ♥ uma das opções quando o botão MAPA é selecionado
    private void jescolhaLugarFUNDO4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jescolhaLugarFUNDO4MouseClicked
        
            imagem.trocar(tempCidade.fundo, jFUNDO);
            jTITULO.setText(tempCidade.nomeCidade);
            jtextoScrollAZUL.setVisible(true);
            jtextoAZUL.setText(tempCidade.cidadeDescricao);
            jSAIBAMAIS.setVisible(true);   
            bLocaisOpcoesOFF();
        
    }//GEN-LAST:event_jescolhaLugarFUNDO4MouseClicked
    
    // ♥ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ opções MAPA    
    // ♥ uma das opções quando o botão MAPA é selecionado
    private void jescolhaLugarFUNDO5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jescolhaLugarFUNDO5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jescolhaLugarFUNDO5MouseClicked
    
    // ♥ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ opções MAPA
    // ♥ uma das opções quando o botão MAPA é selecionado
    private void jescolhaLugarFUNDO6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jescolhaLugarFUNDO6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jescolhaLugarFUNDO6MouseClicked
   
    
        // ♥ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Métodos para habilitar e desabilitar botões
    private void bLocalON (){ //HABILITA E DISPONIBILIZA VISUALIZAÇÃO DO BOTAO LOCAL
        jLOCAIS.setEnabled(true); jLOCAIS.setVisible(true);  
    }    
    
    private void bLocalOFF (){ //HABILITA E DISPONIBILIZA VISUALIZAÇÃO DO BOTAO LOCAL
        jLOCAIS.setEnabled(false); jLOCAIS.setVisible(false); 
    } 
    
    private void bMapaON (){ //HABILITA E DISPONIBILIZA VISUALIZAÇÃO DO BOTAO LOCAL
        jMAPA.setEnabled(true); jMAPA.setVisible(true); 
    } 
    
    private void bMapaOFF (){ //HABILITA E DISPONIBILIZA VISUALIZAÇÃO DO BOTAO LOCAL
        jMAPA.setEnabled(false); jMAPA.setVisible(false); 
    }
    
    private void bPistasON (){ //HABILITA E DISPONIBILIZA VISUALIZAÇÃO DO BOTAO LOCAL
        jPISTAS.setEnabled(true); jPISTAS.setVisible(true); 
    } 
    
    private void bPistasOFF (){ //HABILITA E DISPONIBILIZA VISUALIZAÇÃO DO BOTAO LOCAL
        jPISTAS.setEnabled(false); jPISTAS.setVisible(false); 
    }
    
    private void bLocaisOpcoesOFF(){
        jescolhaLugarFUNDO1.setVisible(false); jescolhaLugarFUNDO1.setEnabled(false);
        jescolhaLugarFUNDO2.setVisible(false); jescolhaLugarFUNDO2.setEnabled(false);
        jescolhaLugarFUNDO3.setVisible(false); jescolhaLugarFUNDO3.setEnabled(false);
    }
    
    private void bMapaOpcoesOFF(){
        jescolhaLugarFUNDO4.setVisible(false); jescolhaLugarFUNDO4.setEnabled(false);
        jescolhaLugarFUNDO5.setVisible(false); jescolhaLugarFUNDO5.setEnabled(false);
        jescolhaLugarFUNDO6.setVisible(false); jescolhaLugarFUNDO6.setEnabled(false);
    }
    
    private void botoesOFF (){
        bPistasOFF();
        bMapaOFF();
        bLocalOFF();
    }
    
    private void bInvestigarON (){ //HABILITA E DISPONIBILIZA VISUALIZAÇÃO DO BOTAO LOCAL
        jINVESTIGAR.setEnabled(true); jINVESTIGAR.setVisible(true); 
    } 
    
    private void bInvestigarOFF (){ //HABILITA E DISPONIBILIZA VISUALIZAÇÃO DO BOTAO LOCAL
        jINVESTIGAR.setEnabled(false); jINVESTIGAR.setVisible(false); 
    }
    
    private void pergaminhoOFF(){
        
        jtextoPERGAMINHO.setVisible(false);
        jCONTINUAR.setVisible(false);
        jtextoScrollPERGAMINHO.setVisible(false);
        jcaixaAZUL.setVisible(true);
        jTITULO.setVisible(true);
        jtextoAZUL.setVisible(true);
        
        
    }
    
    private void investigarON (){
        //BOTOES DOS LOCAIS RECEBEM TEXTO DA CIDADE ATUAL
        jtextoLUGAR1.setText(tempCidade.local1.nome);
        jtextoLUGAR2.setText(tempCidade.local2.nome);
        jtextoLUGAR3.setText(tempCidade.local3.nome);
        
        
        
        jTESTEMUNHA.setVisible(false);
        jtextoLUGAR1.setVisible(true);
        jtextoLUGAR2.setVisible(true);
        jtextoLUGAR3.setVisible(true);
        
        jescolhaLugarFUNDO1.setVisible(true);
        jescolhaLugarFUNDO2.setVisible(true);
        jescolhaLugarFUNDO3.setVisible(true);
      
        jSAIBAMAIS.setVisible(true);
        jMAPA.setVisible(true);   
    }  
    
    private void investigarOFF(){
        jtextoLUGAR1.setVisible(false);
        jtextoLUGAR2.setVisible(false);
        jtextoLUGAR3.setVisible(false);

        jescolhaLugarFUNDO1.setVisible(false); jescolhaLugarFUNDO1.setEnabled(false);
        jescolhaLugarFUNDO2.setVisible(false); jescolhaLugarFUNDO2.setEnabled(false);
        jescolhaLugarFUNDO3.setVisible(false); jescolhaLugarFUNDO3.setEnabled(false);
        jescolhaLugarFUNDO4.setVisible(false); jescolhaLugarFUNDO4.setEnabled(false);
        jescolhaLugarFUNDO5.setVisible(false); jescolhaLugarFUNDO5.setEnabled(false);
        jescolhaLugarFUNDO6.setVisible(false); jescolhaLugarFUNDO6.setEnabled(false);
     
        //jCONVERSAR.setVisible(false);
        jSAIBAMAIS.setVisible(true);
        jMAPA.setVisible(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jCONTINUAR;
    private javax.swing.JLabel jFUNDO;
    private javax.swing.JLabel jINVESTIGAR;
    private javax.swing.JLabel jLOCAIS;
    private javax.swing.JLabel jMAPA;
    private javax.swing.JLabel jPISTAS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jSAIBAMAIS;
    private javax.swing.JLabel jTESTEMUNHA;
    private javax.swing.JTextField jTITULO;
    private javax.swing.JLabel jcaixaAZUL;
    private javax.swing.JLabel jcaixaGrandeAZUL2;
    private javax.swing.JLabel jescolhaLugarFUNDO1;
    private javax.swing.JLabel jescolhaLugarFUNDO2;
    private javax.swing.JLabel jescolhaLugarFUNDO3;
    private javax.swing.JLabel jescolhaLugarFUNDO4;
    private javax.swing.JLabel jescolhaLugarFUNDO5;
    private javax.swing.JLabel jescolhaLugarFUNDO6;
    private javax.swing.JTextArea jtextoAZUL;
    private javax.swing.JLabel jtextoLUGAR1;
    private javax.swing.JLabel jtextoLUGAR2;
    private javax.swing.JLabel jtextoLUGAR3;
    private javax.swing.JTextArea jtextoPERGAMINHO;
    private javax.swing.JScrollPane jtextoScrollAZUL;
    private javax.swing.JScrollPane jtextoScrollPERGAMINHO;
    // End of variables declaration//GEN-END:variables
}

